### ISSUE TITLE
OpenAPI specification file with header markdown errors on site load

### ISSUE THREAD

**Issue by adampridmore** [alphagov/tdt-documentation#156]
If you use an OpenAPI specification file in a tech doc and use a markdown header in a 'description' field, it errors when the site loads. 

Error:
```
TypeError: no implicit conversion of nil into String
        /usr/local/lib/ruby/gems/2.7.0/gems/govuk_tech_docs-2.3.0/lib/govuk_tech_docs/table_of_contents/heading.rb:16:in `+'
        /usr/local/lib/ruby/gems/2.7.0/gems/govuk_tech_docs-2.3.0/lib/govuk_tech_docs/table_of_contents/heading.rb:16:in `href'
        /usr/local/lib/ruby/gems/2.7.0/gems/govuk_tech_docs-2.3.0/lib/govuk_tech_docs/table_of_contents/heading_tree_renderer.rb:23:in `render_tree'
        /usr/local/lib/ruby/gems/2.7.0/gems/govuk_tech_docs-2.3.0/lib/govuk_tech_docs/table_of_contents/heading_tree_renderer.rb:31:in `block in render_tree'
...
```

Example OAS file:

```
openapi: 3.0.0
info:
  title: my title
  version: "1.0"
  description: "# My markdown heading"
paths:
  /my-path:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
```

Note: If you remove the `#` prefix in the description value above the site load correctly.

**Comment by m-green** [comment]
This was now fixed in https://github.com/alphagov/tech-docs-gem/pull/281. Thanks for raising this with us @adampridmore.
